export const ADD_TO_CART = "ADD_TO_CART";
export const UPDATE_CART_ITEM = "UPDATE_CART_ITEM";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const RESET_CART = "RESET_CART";

export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";
export const UPDATE_BILLING_INFO = "UPDATE_BILLING_INFO";
